import numpy as np
x = np.zeros((2,3))
print(x)
y = np.ones([2,3,3],dtype='int32')
print(y)
z = np.empty([1,3])
print(z)
m = np.arange(10)
print(m)
n = np.arange(-5,10,5)
print(n)
o = np.linspace(0,20,5)
print(o)
p = np.full([2,5],13)
print(p)